### ISSUE TITLE
STOP running train.py

### ISSUE THREAD

**Issue by raialvaro** [remicres/sr4rs#14]
Hi again Remi,

Finally I have managed to create the docker images and launch its command to create the patches.

Once created, I run the train.py code and it gets stuck in this library.

![image](https://user-images.githubusercontent.com/71493478/111601731-f1877380-87d2-11eb-8b69-539e9d5ef078.png)

Once created, I run the train.py code but it stops at epoch 0, just when it opens the libcublas.so library. 10

Do you know what may be happening and how it could be solved?

Thank so much!

**Comment by remicres** [comment]
Hi @raialvaro ,
If you have no error message, and the `train.py` is still running, then all seems fine.
Maybe you can use the `--logdir` to some directory. After that, start a tensorboard to monitor that you can see losses (L1, L2, Gan, etc)

**Comment by raialvaro** [comment]
You're right!

I had made patches too big that it took a long time to move to the next epoch!

I have reduced the size and now it shows the epoch

![image](https://user-images.githubusercontent.com/71493478/111625335-07099700-87ed-11eb-858a-bcbcebe64039.png)

Sorry for the inconvenience and thanks again!

**Comment by remicres** [comment]
No problem.
On a V100 GPU, if I use say `64x64` (LR) --> `256x256` (HR) patches, one epoch is approximately 25 minutes for 5k samples and batch size 4.
