### ISSUE TITLE
could you send me this file`stacked_channels_4328_10m.tif`？

### ISSUE THREAD

**Issue by yujmo** [remicres/sr4rs#49]
Hello, could you send me this file`stacked_channels_4328_10m.tif`? 
My data preprocessing has always had problems, so I want to see your data preprocessing results.
My Email is `yujmo@qq.com`

**Comment by remicres** [comment]
Hi,

The `stacked_channels_4328_10m.tif` results from the concatenation of 10m spacing spectral bands of Sentinel-2, in the following order:
1. Band 4 (B4) aka red
2. Band 3 (B3) aka green
3. Band 2 (B2) aka blue
4. Band 8 (B8) aka near infra-red

You can use the tool of your choice to perform the concatenation (e.g. OTB with `ConcatenateImage` [[1](https://www.orfeo-toolbox.org/CookBook/Applications/app_ConcatenateImages.html)] or GDAL with `gdal_merge.py` [[2](https://gdal.org/programs/gdal_merge.html)])
