### ISSUE TITLE
Error occurred during tensor to image

### ISSUE THREAD

**Issue by ozeankeeper** [remicres/sr4rs#50]
Hello Rémi,

I absolutely appreciate the work done here and super resolution imagery would be very useful for fine grained classification.

When I use the pre-trained model to infer, I encountered the following problem,

> Writing test.tif??&streaming:type=tiled&streaming:sizemode=height&streaming:sizevalue=512...: 0% [                                                  ]2022-10-14 06:41:32.596993: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101
> Traceback (most recent call last):
>   File "sr4rs/code/sr.py", line 100, in <module>
>     infer.ExecuteAndWriteOutput()
>   File "/opt/otbtf/lib/otb/python/otbApplication.py", line 2451, in ExecuteAndWriteOutput
>     return _otbApplication.Application_ExecuteAndWriteOutput(self)
> RuntimeError: Exception thrown in otbApplication Application_ExecuteAndWriteOutput: /src/otb/otb/Modules/Remote/otbtf/include/otbTensorflowMultisourceModelFilter.hxx:496:
> itk::ERROR: TensorflowMultisourceModelFilter(0x345f6b0): Error occurred during tensor to image conversion.
> Context: Output image buffered region: ImageRegion (0x7ffe564c6330)
>   Dimension: 2
>   Index: [0, 0]
>   Size: [512, 512]
> 
> Input #0:
> Requested region: ImageRegion (0x7ffe564c6360)
>   Dimension: 2
>   Index: [0, 1]
>   Size: [128, 127]
> 
> Tensor "lr_input": Tensor shape is {1, 127, 128, 4} data type is 1 (float)
> User placeholders:
> Error:
> itk::ExceptionObject (0x5a27ae30)
> Location: "unknown" 
> File: /src/otb/otb/Modules/Remote/otbtf/include/otbTensorflowCopyUtils.cxx
> Line: 227
> Description: itk::ERROR: Number of elements in the tensor is 583680 but image outputRegion has 1048576 values to fill.
> Buffer region is: 
> ImageRegion (0x7ffe564c6540)
>   Dimension: 2
>   Index: [0, 0]
>   Size: [512, 512]
> 
> Number of components in the output image: 4
> Tensor shape: {1, 380, 384, 4}
> Please check the input(s) field of view (FOV), the output field of expression (FOE), and the  output spacing scale if you run the model in fully convolutional mode (how many strides in your model?)

Could you help me with that? Thank you very much.

**Comment by remicres** [comment]
hi @ozeankeeper 

This looks like a bug.
In order to investigate, could you please show us the following:
- command line used
- full log

Thanks

**Comment by ozeankeeper** [comment]
hi @remicres 

Here is my full log. 
[log.txt](https://github.com/remicres/sr4rs/files/9828918/log.txt)


And my output of the gdalinfo command.
[output.txt](https://github.com/remicres/sr4rs/files/9828920/output.txt)

**Comment by remicres** [comment]
Your input image has no geospatial metadata.
OTBTF needs a coordinates reference system, image origin and physical spacing to work properly.
If you just want tu run the model over small non-geospatial patches, I advise you to use python instead.

**Comment by ozeankeeper** [comment]
Thanks! @remicres 
Do you mean that I need to apply sr4rs directly on python？Pardon my ignorance but how？

**Comment by remicres** [comment]
you have two options.
- build the graph and use the checkpoints of the pre-trained model (see how `train.py` does)
- use the savedmodel

**Comment by ozeankeeper** [comment]
hi @remicres 
  I need to express my sincere apology to you for not replying to you in time recently due to some private matters. 
  I solved my problem with your help, and it has been running successfully. Thank you very much for your reply!

**Comment by Eliaukyxw** [comment]
hi, @ozeankeeper 
I'm sorry to bother you. How do you solve this problem? I encountered a similar error when generating images. Looking forward to your reply！
![da8226e97c789288a2c40d6171dcf4f](https://user-images.githubusercontent.com/117817033/223906856-0c69ee74-62ba-459c-b078-eb651ecf92d3.png)

**Comment by ozeankeeper** [comment]
hi,
This problem is caused by your improper input images. You must use the remote sensing images with geo-metadatas and 4 bands. Maybe you can check your input images whether it includes relevant infomation by 'gdalinfo' command (Google can provide instructions). Here is an example of my RS-image about 'gdalinfo' command.&nbsp;
Hope you can help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "remicres/sr4rs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 中午11:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [remicres/sr4rs] Error occurred during tensor to image (Issue #50)





 
hi, @ozeankeeper
 I'm sorry to bother you. How do you solve this problem? I encountered a similar error when generating images. Looking forward to your reply！

**Comment by Eliaukyxw** [comment]
Hi, @ozeankeeper :
I am terribly sorry for replying you so late. I successfully solved the problem with your help. Thank you again!
