### ISSUE TITLE
pretrained model test error 

### ISSUE THREAD

**Issue by dockoS** [remicres/sr4rs#56]
Hi @remicres,
Thank you for your great work, it is very helpful.
I want to test my S2 image in the pre-trained model. I download the saved model and run the script for the sr.py in the readme.
But I get this error:

commande: python sr.py --savedmodel ../../sr4rs_sentinel2_bands4328_france2020_savedmodel --input ../../RGBN.tif --output ../../RGBN_2.5m.tif --encoding unsigned_short  -_2.5m.tif 

Output:
19 20:28:55 (WARNING): Streaming configuration through extended filename is used. Any previous streaming configuration (ram value, streaming mode ...) will be ignored.

2022-12-19 20:28:55 (INFO): File ../../RGBN_2.5m.tif will be written in 12 blocks of 512x512 pixels

Writing ../../RGBN_2.5m.tif?&streaming:type=tiled&streaming:sizemode=height&streaming:sizevalue=512...: 0% [                                                  ]2022-12-19 20:29:01.768564: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 416808960 exceeds 10% of free system memory.

2022-12-19 20:29:04.694963: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 416808960 exceeds 10% of free system memory.

2022-12-19 20:29:04.695822: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 1667235840 exceeds 10% of free system memory.

2022-12-19 20:29:09.617014: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 416808960 exceeds 10% of free system memory.

2022-12-19 20:29:10.663083: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 416808960 exceeds 10% of free system memory.

Traceback (most recent call last):

  File "sr.py", line 103, in <module>

    infer.ExecuteAndWriteOutput()

  File "/opt/otbtf/lib/otb/python/otbApplication.py", line 2451, in ExecuteAndWriteOutput

    return _otbApplication.Application_ExecuteAndWriteOutput(self)

RuntimeError: Exception thrown in otbApplication Application_ExecuteAndWriteOutput: /src/otb/otb/Modules/Remote/otbtf/include/otbTensorflowMultisourceModelFilter.hxx:496:

itk::ERROR: TensorflowMultisourceModelFilter(0x43b5b290): Error occurred during tensor to image conversion.

Context: Output image buffered region: ImageRegion (0x7ffe64ead650)

  Dimension: 2

  Index: [0, 0]

  Size: [512, 512]

Input #0:

Requested region: ImageRegion (0x7ffe64ead680)

  Dimension: 2

  Index: [0, 473]

  Size: [160, 159]

Tensor "lr_input": Tensor shape is {1, 159, 160, 4} data type is 1 (float)

User placeholders:

Error:

itk::ExceptionObject (0x64668220)

Location: "unknown" 

File: /src/otb/otb/Modules/Remote/otbtf/include/otbTensorflowCopyUtils.cxx

Line: 227

Description: itk::ERROR: Number of elements in the tensor is 1040384 but image outputRegion has 1048576 values to fill.

Buffer region is: 

ImageRegion (0x7ffe64ead860)

  Dimension: 2

  Index: [0, 0]

  Size: [512, 512]

Number of components in the output image: 4

Tensor shape: {1, 508, 512, 4}

Please check the input(s) field of view (FOV), the output field of expression (FOE), and the  output spacing scale if you run the model in fully convolutional mode (how many strides in your model?) 

How can I handle this error?

**Comment by remicres** [comment]
hi @dockoS ,

looks duplicated of #50 

> Your input image has no geospatial metadata.
OTBTF needs a coordinates reference system, image origin and physical spacing to work properly.
If you just want tu run the model over small non-geospatial patches, I advise you to use python instead.

**Comment by dockoS** [comment]
Thank you @remicres, 
It works well,  I change the input to have geospatial metadata.
Merci beaucoup.
