### ISSUE TITLE
 How to get seamless HR image

### ISSUE THREAD

**Issue by Eliaukyxw** [remicres/sr4rs#61]
Hi, @remicres 
When I reconstruct NDVI image with super resolution, the model achieves good results.
However, there is a problem. When the parameter ts is 64 patches, there will be boundaries when multiple patches are stitched together, as shown in the figure below. How can I solve this problem? Looking forward to your reply.
![屏幕截图 2023-03-07 103807](https://user-images.githubusercontent.com/117817033/223305730-039d97d4-2c7f-46ff-91d4-a9caa8f94f1f.png)

**Comment by remicres** [comment]
Hi @Eliaukyxw 
That should be really easy to fix: Just increase the `--pad` parameter of `sr.py` to 128 or 256 (it should be enough).
The image will be a little bit longer to process though.

**Comment by Eliaukyxw** [comment]
Great remi ! This method works really well. Thanks for your timely help.
