### ISSUE TITLE
update docker image tags in readme

### ISSUE THREAD

**Issue by sheeceg** [remicres/sr4rs#65]
from docker registery [mdl4eo/otbtf](https://hub.docker.com/r/mdl4eo/otbtf) latest version of docker is 3.3.3, but the readme still refers to 2.5, 
I think following line:

`docker run -ti --runtime=nvidia mdl4eo/otbtf2.5:gpu bash`

needs to be updated to:

`docker run -ti --runtime=nvidia mdl4eo/otbtf::latest bash`

**Comment by remicres** [comment]
thanks!

we are currently improving the documentation in depth, we will fix that too.
