### ISSUE TITLE
The meaning of dis_loss

### ISSUE THREAD

**Issue by Eliaukyxw** [remicres/sr4rs#66]
Hi, @remicres 
   Does dis_loss mean total loss? Why is its loss picture different from other losses? There is an increasing trend.

**Comment by remicres** [comment]
Hi @Eliaukyxw 

`dis_loss` stands for discriminator loss.

**Comment by Eliaukyxw** [comment]
Oh, I got it! Discriminator loss need to be maximized to better distinguish between real and fake images.
