### ISSUE TITLE
Data pre-processing

### ISSUE THREAD

**Issue by aleksmirosh** [remicres/sr4rs#70]
Hi!
I am just new in the field of remote sensors. I am working on the model for SR but I can not actually get any nice results, and I am really glad I found yours as your output looks really good. 
Can I ask you about your data preprocessing? Did you normalize data from remote sensors to be in range [0, 1]? Or do you train it as it is?

**Comment by remicres** [comment]
Hi @aleksmirosh ,

You can take a look in the following issues, where this matter has already been addressed: #47 , #38
