### ISSUE TITLE
Make patch shapefiles

### ISSUE THREAD

**Issue by atlasul-hub** [remicres/sr4rs#71]
Hi @remicres, how are you?
I'm assembling the files to train the model (SR4RS) for my study area, but I'm having difficulty creating the patch shapefiles, could you send me an example file? I didn't find an example file, just the tutorial: https://mdl4eo.irstea.fr/2019/03/29/enhancement-of-sentinel-2-images-at-1-5m/

Thank you for the assistance!

**Comment by remicres** [comment]
Hi @atlasul-hub ,

Tu create patches you can use the `PatchesExtraction` application (see [here](https://otbtf.readthedocs.io/en/latest/app_sampling.html#patchesextraction)) with `OTB_TF_NSOURCES=2` for the HR and LR images.
