### ISSUE TITLE
SR image full of blobs

### ISSUE THREAD

**Issue by EmanuelCastanho** [remicres/sr4rs#77]
Hi, great work on sr4rs!

I am testing on images of different locations and in the bellow example I noticed that the result SR image is full of blobs, is this related with some interpolation factor?

LR:
![test_1_print](https://github.com/remicres/sr4rs/assets/69935277/e08e434c-f6cc-45cf-a31a-b9142d1edae8)

SR:
![test_1_sr_print](https://github.com/remicres/sr4rs/assets/69935277/d131e7d7-a459-4072-a21f-794916130f5f)

**Comment by remicres** [comment]
hi @EmanuelCastanho 

thanks. the model is for Sentinel-2 images, 10m spacing.

in case you have different kind of image, you might be interested to fine tune or retrain the model with your images.

**Comment by EmanuelCastanho** [comment]
@remicres the image I present as LR is from Sentinel-2 resampled to 10 meters.
